# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
        - auth
        # - beer-api
        # - beer-import
        # - cocktail-api
        # - cocktail-import
        - frontend
        # - supermarket-api
        # - supermarket-import
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        - 12.x
        - 14.x
        - 15.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ matrix.folder }}-${{ hashFiles('${{ matrix.folder }}/package-lock.json') }}

    - run: npm ci
      working-directory: ${{ matrix.folder }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.folder }}
    - run: npm test
      working-directory: ${{ matrix.folder }}
    - run: npm run coverage
      working-directory: ${{ matrix.folder }}
