# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
        - auth
        # - beer-api
        - beer-import
        # - cocktail-api
        # - cocktail-import
        - frontend
        # - supermarket-api
        # - supermarket-import
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        - 12.x
        - 14.x
        - 15.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ matrix.folder }}-${{ hashFiles('${{ matrix.folder }}/package-lock.json') }}

    - run: npm ci
      working-directory: ${{ matrix.folder }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.folder }}
    - run: npm run test --if-present
      working-directory: ${{ matrix.folder }}
    - run: npm run lint --if-present
      working-directory: ${{ matrix.folder }}

    - uses: codecov/codecov-action@v1
      with:
        directory: ${{ matrix.folder }}

  docker:
    if: github.ref == 'refs/heads/master' || github.event == 'push'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
        - auth
        # - beer-api
        - beer-import
        # - cocktail-api
        # - cocktail-import
        - frontend
        # - supermarket-api
        # - supermarket-import
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bierteamtravis
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.folder }}
        builder: ${{ steps.buildx.outputs.name }}
        push: false
        tags:  bierteam/${{ matrix.folder }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    runs-on: ubuntu-latest
    needs: [ test, docker ]
    if: github.ref == 'refs/heads/master' || github.event == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt kubeconfig
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output /tmp/kubeconfig kubernetes/kubeconfig.gpg
      - name: Decrypt secrets.yaml
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output kubernetes/secrets.yaml kubernetes/secrets.yaml.gpg
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: /tmp/kubeconfig # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
        id: setcontext
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.2
        with:
          manifests: kubernetes/*.yaml
          kubectl-version: latest