# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
    - "auth/**"
    - "beer-api/**"
    - "beer-import/**"
    - "cocktail-api/**"
    - "cocktail-import/**"
    - "frontend/**"
    - "supermarket-api/**"
    - "supermarket-import/**"
    - ".github/**"
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        - 12.x
        - 14.x
        - 15.x
        folder:
        - auth
        # - beer-api
        - beer-import
        - cocktail-api
        # - cocktail-import
        - frontend
        - supermarket-api
        # - supermarket-import
        exclude:
        - os: [ macos-latest, windows-latest ]
          node-version: [ 12.x, 14.x ]

    steps:
    - name: Echo site details
      env:
        FOLDER: ${{ matrix.folder }}
        OS: ${{ matrix.os }}
        NODE: ${{ matrix.node-version }}
      run: echo $FOLDER $OS $NODE $PWD
      working-directory: ${{ matrix.folder }}

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{ matrix.folder }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.folder }}
    - run: npm test
      working-directory: ${{ matrix.folder }}
