# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
    - "auth/**"
    - "beer-api/**"
    - "beer-import/**"
    - "cocktail-api/**"
    - "cocktail-import/**"
    - "frontend/**"
    - "supermarket-api/**"
    - "supermarket-import/**"
    - ".github/**"
  pull_request:
    branches: [ master ]


jobs:
  build:
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        - 12.x
        - 14.x
        - 15.x
        folders:
        - "auth"
        # - "beer-api"
        - "beer-import"
        - "cocktail-api"
        # - "cocktail-import"
        - "frontend"
        - "supermarket-api"
        # - "supermarket-import"
        include:
        - os: macos-latest
          node: 15.x
        - os: windows-latest
          node: 15.x

    steps:
    - name: Echo site details
      env:
        FOLDER: ${{ matrix.folder }}
        NODE: ${{ matrix.os }}
        OS: ${{ matrix.node-version }}
      run: echo $FOLDER $OS $NODE $PWD

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
