# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
    - "auth/**"
    - "beer-api/**"
    - "beer-import/**"
    - "cocktail-api/**"
    - "cocktail-import/**"
    - "frontend/**"
    - "supermarket-api/**"
    - "supermarket-import/**"
    - ".github/**"
  pull_request:
    branches: [ master ]


jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      folders: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          auth: /auth
          beer-import: /beer-import
          cocktail-api: /cocktail-api
          frontend: /frontend
          supermarket-api: /supermarket-api
  test:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['package1', 'package2'] if both package folders contains changes
        folder: ${{ fromJson(needs.changes.outputs.folders) }}
        # folder:
        # - /auth
        # # - /beer-api
        # - /beer-import
        # - /cocktail-api
        # # - /cocktail-import
        # - /frontend
        # - /supermarket-api
        # # - /supermarket-import
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        - 12.x
        - 14.x
        - 15.x

    steps:
    - name: Echo site details
      env:
        FOLDER: ${{ matrix.folder }}
        NODE: ${{ matrix.node-version }}
      run: echo $FOLDER $NODE $PWD
      working-directory: ${{ matrix.folder }}

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{ matrix.folder }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.folder }}
    - run: npm test
      working-directory: ${{ matrix.folder }}
